### PR TITLE
Bring libzerocash in tree

### PR DESCRIPTION
**Pull request by ebfull**
* Removes libsnark's dependencies on `ate-pairing`, `xbyak` and `crypto++`. (These dependencies are either unnecessary for libsnark or our curve doesn't use them.) `crypto++` is still a dependency for libzerocash *for now*.
* Brings libzerocash in tree at `src/zerocash` and reorganize the directory layout. (**Somebody still needs to LGTM that I `cp -r`'d this correctly.**)
* Integrates libzerocash's building alongside other components of Bitcoin such as `libbitcoinconsensus` and `libbitcoin_wallet`.
* Compiles tests and utilities for zerocash (**Still need to decide where these tests should be run from, and if we need to add a new buildbot waterfall**)

### CODE REVIEW

**Comment by ebfull** [comment]
I've fixed nits and now it should compile our utilities and tests for zerocash. I'm not sure what our test suite should test though. Should we make a new waterfall for the zkSNARK stuff and put the rest in `full-test-suite`?

**Comment by defuse** [comment]
The only unaddressed issues is including those `.tcc` files into one of the two source file lists.

**Comment by nathan-at-least** [comment]
I haven't reviewed the full PR. I just verified that the contents of the first commit do match the named libzerocash commit:

```
$ diff -ru ./libzerocash-pristine/ ./zc/wip/src/zerocash/
Only in ./libzerocash-pristine/: .git
```

**Comment by nathan-at-least** [comment]
ACK on code review; currently doing local build/test.

**Comment by ebfull** [comment]
This can be merged as soon as someone ACK's `57220d0`.

**Pull request merged**
