### PR TITLE
Add feature to resume downloads of params files.

### LINKED ISSUE #654: wget in fetch-params.sh should use --continue option
I experienced difficulty when downloading the 2GB proving key. I strongly recommend to add --continue to the wget, and disable the filename check. Only in this way, I was able to get the proving key.

### PR DESCRIPTION
**Pull request by nathan-at-least**
closes #654

### CODE REVIEW

**Comment by nathan-at-least** [comment]
We're going to switch to a user-contributed ``fetch-params.py`` over in #657, so I'll re-implement these features there.

**Comment by ebfull** [comment]
We'll keep both in tree.

**Comment by nathan-at-least** [comment]
Note: keeping two script in tree works for now but is a temporary measure and we should remove one.

**Comment by daira** [comment]
This saved me a bunch of time yesterday, thanks :-)

**Pull request merged**
